require 'shellwords'
require 'repla'
require Repla::shared_test_resource("ruby/test_constants")
require Repla::Tests::TEST_HELPER_FILE

task :default => ['logger:tests']

namespace :logger do
  
  task :tests => [:clean_up]

  task :test_logger do
    logger_tests_file = File.join(File.dirname(__FILE__), "tc_logger.rb")
    ruby Shellwords.escape(logger_tests_file)
  end

  task :clean_up => [:test_logger] do
    Repla::Tests::Helper::quit
  end
end
