require_relative '../bundle/bundler/setup'
require 'repla'

require 'repla/test'
require Repla::Test::HELPER_FILE
require 'shellwords'

task default: ['markdown:tests']

namespace :markdown do
  task tests: [:clean_up]

  task :test_controller do
    server_tests_file = File.join(File.dirname(__FILE__),
                                  'tc_server.rb')
    ruby Shellwords.escape(server_tests_file)
  end

  task test_plugin: [:test_controller] do
    plugin_tests_file = File.join(File.dirname(__FILE__), 'tc_plugin.rb')
    ruby Shellwords.escape(plugin_tests_file)
  end

  task clean_up: [:test_plugin]
end
