# A sample Gemfile
source 'https://rubygems.org'
ruby '2.4.1'
gem 'kramdown'
gem 'listen'
gem 'raster'
gem 'repla'
# "nio" is a dependency of listen, before adding it explicitely here, new
# machines were getting a load error.
gem 'nio'
