# A sample Gemfile
source "https://rubygems.org"
ruby '2.3.7'
gem "repla"
gem "redcarpet"
gem "listen"
gem "nio" # "nio" is a dependency of listen, before adding it explicitely here, new machines were getting a load error.
